# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  - portfolio

# Pay very close attention to the spacing here. It matters.
skills:
  - name: Java
    level: 5
  - name: Javascript
    level: 5
  - name: HTML/CSS
    level: 4
  - name: SQL
    level: 4
  - name: Sencha Ext JS
    level: 4
  - name: Agile Methodology
    level: 4
  - name: C#
    level: 4
  - name: C++
    level: 3
  - name: Angular 2
    level: 3
  - name: Android SDK
    level: 3
  - name: Bootstrap CSS
    level: 3
  - name: JQuery
    level: 3
  - name: AJAX
    level: 3
  - name: Jekyll
    level: 2
  - name: nodeJS
    level: 2
  - name: python
    level: 2

